name: Django Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          python-version: "3.10"
          activate-environment: myenv

      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          pip install -r requirements.txt

      - name: Create .env file
        run: |
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> .env
          echo "PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }}" >> .env

      - name: Run Migrations
        shell: bash -l {0}
        run: |
          python manage.py migrate

      - name: Run Tests
        shell: bash -l {0}
        run: |
          python manage.py test chatbot_app
